export type FanMindLanguage = "de" | "en";

export const fanmindLanguages: FanMindLanguage[] = ["de", "en"];

export function getFanMindLanguage(lang?: string | string[] | null): FanMindLanguage {
  const value = Array.isArray(lang) ? lang[0] : lang;
  return value === "en" ? "en" : "de";
}

export function landingPath(language: FanMindLanguage, hash = "") {
  return language === "en" ? `/?lang=en${hash}` : `/${hash}`;
}

export function localizedPath(path: "/login" | "/register" | "/forgot-password" | "/reset-password", language: FanMindLanguage, query = "") {
  const separator = query ? "&" : "?";
  return language === "en" ? `${path}${query}${separator}lang=en` : `${path}${query}`;
}

export const fanmindCopy = {
  de: {
    nav: {
      product: "Produkt",
      problems: "Probleme",
      conversion: "Conversion",
      integrations: "Integrationen",
      pricing: "Preise",
      roadmap: "Roadmap",
      contact: "Kontakt",
      login: "Login",
      register: "Registrieren",
    },
    login: {
      title: "Workspace öffnen",
      subtitle: "Melde dich an und öffne deinen FanMind Workspace.",
      email: "E-Mail",
      password: "Passwort",
      submit: "Einloggen",
      demo: "Kostenlos testen",
      registerPrompt: "Noch keinen Zugang?",
      registerLink: "Registrieren",
      landing: "Zur Startseite",
      notice: "Facebook Messenger kann angebunden werden. Antworten werden manuell geprüft und extern gesendet; kein automatisches Senden.",
    },
    register: {
      title: "Zugang vormerken",
      subtitle: "Sichere dir Zugang zum KI-CRM für Creator, Clubs, Events und Fan-Communities.",
      name: "Name",
      email: "E-Mail",
      password: "Passwort",
      organization: "Unternehmen / Club / Creator-Name",
      role: "Rolle / Zielgruppe",
      message: "Nachricht optional",
      submit: "Konto erstellen",
      loginPrompt: "Schon Zugang?",
      loginLink: "Zum Login",
      landing: "Zur Startseite",
      success: "Dein FanMind-Konto wurde angelegt.",
    },
  },
  en: {
    nav: {
      product: "Product",
      problems: "Problems",
      conversion: "Conversion",
      integrations: "Integrations",
      pricing: "Pricing",
      roadmap: "Roadmap",
      contact: "Contact",
      login: "Login",
      register: "Sign up",
    },
    login: {
      title: "Open workspace",
      subtitle: "Sign in and open your FanMind workspace.",
      email: "Email",
      password: "Password",
      submit: "Log in",
      demo: "Try for free",
      registerPrompt: "No access yet?",
      registerLink: "Sign up",
      landing: "Back to homepage",
      notice: "Facebook Messenger can be connected. Replies are reviewed manually and sent externally; no automatic sending.",
    },
    register: {
      title: "Request access",
      subtitle: "Secure access to the AI CRM for creators, clubs, events and fan communities.",
      name: "Name",
      email: "Email",
      password: "Password",
      organization: "Company / Club / Creator name",
      role: "Role / target group",
      message: "Message optional",
      submit: "Create account",
      loginPrompt: "Already have access?",
      loginLink: "Log in",
      landing: "Back to homepage",
      success: "Your FanMind account has been created.",
    },
  },
} as const;

const englishCopy: Record<string, string> = {
  "Produkt": "Product",
  "Funktionen": "Features",
  "CSV-Import & Kontaktwissen": "CSV import & contact knowledge",
  "Probleme": "Problems",
  "Preise": "Pricing",
  "Kontakt": "Contact",
  "Registrieren": "Sign up",
  "Die intelligente Fan-Management Plattform": "The intelligent fan management platform",
  "Das KI-CRM für": "The AI CRM for",
  "und": "and",
  "FanMind bündelt Kontakte, Gespräche, Kontaktwissen, Segmente, Follow-ups, CSV-Import und Roadmap in einer intelligenten Plattform – damit aus Fans echte Beziehungen und messbare Conversions werden.": "FanMind brings contacts, conversations, contact knowledge, segments, follow-ups, CSV import and the roadmap together in one intelligent platform – turning fans into real relationships and measurable conversions.",
  "Demo ansehen": "Watch demo",
  "Early Access anfragen": "Request access",
  "Zugang": "Access",
  "Zugang sichern": "Request access",
  "In Kürze": "Coming soon",
  "Zugang unverbindlich für deinen Creator-, Club- oder Event-Use-Case an.": "Request access without obligation for your creator, club or event use case.",
  "Roadmap-Auswertung · In Kürze": "Roadmap reporting · coming soon",
  "Gibt es Zugang oder eine Demo?": "Is there access or a demo?",
  "Ja. Du kannst eine Demo oder Zugang anfragen, damit wir FanMind mit deinem konkreten Use Case und deinen Fan-Prozessen einordnen.": "Yes. You can request a demo or access so we can assess FanMind with your specific use case and fan processes.",
  "Für wen ist FanMind gedacht?": "Who is FanMind for?",
  "FanMind ist für Creator, Clubs, Agenturen und Brands gedacht, die Fan-Kommunikation professionell verwalten und strukturieren wollen – vom ersten Pilot bis zum wachsenden Team.": "FanMind is for creators, clubs, agencies and brands that want to manage and structure fan communication professionally – from the first pilot to a growing team.",
  "Kann FanMind E-Mail, WhatsApp und Chat verbinden?": "Can FanMind connect email, WhatsApp and chat?",
  "E-Mail, Kontakte, CSV-Import und zentrale Gesprächsnotizen stehen in der aktuellen Version im Fokus. Weitere Kanäle wie WhatsApp, Social DMs und Community-Chats sind als Roadmap transparent markiert.": "Email, contacts, CSV import and central conversation notes are the current-version focus. Additional channels such as WhatsApp, social DMs and community chats are transparently marked as roadmap items.",
  "Sendet die KI automatisch Nachrichten?": "Does the AI send messages automatically?",
  "Nein. FanMind bereitet KI-Vorschläge vor, aber dein Team prüft Inhalte bewusst und gibt Kommunikation selbst frei. Es gibt keinen ungeprüften automatischen Versand.": "No. FanMind prepares AI suggestions, but your team reviews content deliberately and approves communication itself. There is no unchecked automatic sending.",
  "Wie schützt FanMind meine Daten?": "How does FanMind protect my data?",
  "FanMind ist mit Datenschutz-Fokus, klaren Freigaben und EU-orientierten Produktprinzipien konzipiert. Sensible Workflows werden bewusst transparent gehalten.": "FanMind is designed with privacy focus, clear approvals and EU-oriented product principles. Sensitive workflows are kept deliberately transparent.",
  "Kann ich mehrere Profile oder Kunden verwalten?": "Can I manage multiple profiles or clients?",
  "Mehrere Profile und Kunden sind vor allem für Growth- und Agency-Workflows vorgesehen. Im Pilot klären wir gemeinsam, welche Struktur für dein Team sinnvoll ist.": "Multiple profiles and clients are mainly planned for growth and agency workflows. In the pilot, we define together which structure makes sense for your team.",
  "Kann ich bestehende Kontakte importieren?": "Can I import existing contacts?",
  "Ja, Kontakt-Import per CSV ist Teil des Produktfokus. Feld-Zuordnung, Validierung und größere Import-Workflows werden schrittweise ausgebaut.": "Yes, contact import via CSV is part of the product focus. Field mapping, validation and larger import workflows will be expanded step by step.",
  "Zugang anfragen": "Request access",
  "Zugang vormerken": "Request access",
  "Erste Referenzen im Aufbau": "First references in progress",
  "FanMind startet mit Pilotmarken und echten Nutzerstimmen. Öffentliche Google-Bewertungen werden angezeigt, sobald das Google-Unternehmensprofil live ist.": "FanMind is starting with pilot brands and real user feedback. Public Google reviews will be shown as soon as the Google Business Profile is live.",
  "Erste Pilotmarke": "First pilot brand",
  "Google Bewertungen": "Google reviews",
  "in Vorbereitung": "in preparation",
  "Bewertungen": "reviews",
  "FanMind Referenzen im Aufbau": "FanMind references in progress",
  "FanMind startet mit echten Pilotnutzern und öffentlichen Bewertungen. Das Google-Unternehmensprofil ist eingerichtet und wird sichtbar, sobald die Verifizierung abgeschlossen ist.": "FanMind is starting with real pilot users and public reviews. The Google Business Profile is set up and will become visible once verification is complete.",
  "Google Unternehmensprofil": "Google Business Profile",
  "In Prüfung": "Under review",
  "Öffentliche Bewertungen werden angezeigt, sobald das Profil live ist.": "Public reviews will be shown as soon as the profile is live.",
  "Kundenstimmen": "Customer voices",
  "Bald verfügbar": "Available soon",
  "Echte Rückmeldungen von ersten Testnutzern werden hier später eingebunden.": "Real feedback from first test users will be added here later.",
  "bei Google": "on Google",
  "echte Bewertungen": "real reviews",
  "Bei Google bewerten": "Review on Google",
  "Willkommen zurück, Nina 👋": "Welcome back, Nina 👋",
  "Heute ist Mittwoch, der 21. Mai 2025 · 09:42 Uhr": "Today is Wednesday, May 21, 2025 · 09:42",
  "● Alle Systeme aktiv": "● All systems active",
  "Letzte 30 Tage⌄": "Last 30 days⌄",
  "+ Neuer Kontakt": "+ New contact",
  "Gesamtfans": "Total fans",
  "Aktive Fans": "Active fans",
  "Offene Follow-ups": "Open follow-ups",
  "Conversion Rate": "Conversion rate",
  "+12,1 % vs. letzter Monat": "+12.1% vs. last month",
  "+8,8 % vs. letzter Monat": "+8.8% vs. last month",
  "12 fällig heute": "12 due today",
  "+1,2 % vs. letzter Monat": "+1.2% vs. last month",
  "Fan-Wachstum": "Fan growth",
  "Entwicklung der Gesamtfans": "Total fan development",
  "Interaktionen nach Kanal": "Interactions by channel",
  "Interaktionen pro Kanal": "Interactions per channel",
  "Nachrichten · Replies · Klicks · Sonstige": "Messages · Replies · Clicks · Other",
  "Sehr starkes Potenzial": "Very strong potential",
  "✦ Nächste beste Aktion": "✦ Next best action",
  "Friend-Ticket vorbereiten": "Prepare friend ticket",
  "→ Hohe Priorität": "→ High priority",
  "Roadmap-Ausblick": "Roadmap preview",
  "keine Vollsuite in der aktuellen Version": "no full suite in the current version",
  "Review-Quote": "Review rate",
  "Follow-up Quote": "Follow-up rate",
  "und viele mehr": "and many more",
  "Vertraut von Top Creator, Clubs & Brands": "Trusted by top creators, clubs and brands",
  "Starte jetzt smartere Fan-Beziehungen.": "Start smarter fan relationships today.",
  "Keine Kreditkarte erforderlich": "No credit card required",
  "Setup in 2 Minuten": "Setup in 2 minutes",
  "Jederzeit kündbar": "Cancel anytime",
  "Early Access sichern": "Request access",
  "DAS PROBLEM HEUTE": "TODAY'S PROBLEM",
  "Fan-Kommunikation ist heute": "Fan communication is",
  "verstreut, unübersichtlich": "scattered and hard to manage",
  "schwer messbar.": "hard to measure.",
  "Viele Kanäle, wenig Kontext und manuelle Prozesse verhindern echte Fan-Nähe, schnelle Antworten und nachhaltiges Wachstum.": "Too many channels, too little context and manual processes get in the way of fan closeness, fast replies and sustainable growth.",
  "DIE LÖSUNG": "THE SOLUTION",
  "verbindet Kontakte, Kontaktwissen, KI, Follow-ups und Roadmap in": "connects contacts, contact knowledge, AI, follow-ups and roadmap in",
  "einem System.": "one system.",
  "Alle Informationen, Interaktionen und Abläufe laufen zusammen – für echte Fan-Beziehungen, die skalieren. KI-Vorschläge bleiben Vorschläge: Der Mensch prüft und gibt frei.": "All information, interactions and workflows come together – for real fan relationships that scale. AI suggestions remain suggestions: a human reviews and approves them.",
  "FanMind in 6 Schritten": "FanMind in 6 steps",
  "Von der ersten Anfrage bis zum geprüften": "From the first request to the reviewed",
  "FanMind verbindet Kontakte, KI und Aktionen in einem System – damit du Beziehungen aufbaust, rechtzeitig reagierst und nächste Schritte nachvollziehbar vorbereitest.": "FanMind connects contacts, AI and actions in one system – so you build relationships, respond in time and prepare next steps transparently.",
  "Auswählen": "Select",
  "Ein System für Beziehungen, Aktionen und Ergebnisse.": "One system for relationships, actions and results.",
  "Use Case Sandra M.": "Sandra M. use case",
  "Aus Interesse wird": "Interest becomes",
  "FanMind verwandelt eine einfache Fan-Frage in den richtigen nächsten Schritt – kontextbasiert, persönlich und messbar erfolgreich.": "FanMind turns a simple fan question into the right next step – context-based, personal and measurably effective.",
  "Käuferin": "Buyer",
  "VIP interessiert": "VIP interested",
  "KI versteht Kontext": "AI understands context",
  "Relevante Insights in Echtzeit.": "Relevant insights in real time.",
  "Next-Best-Action": "Next best action",
  "Die passende Aktion zur richtigen Zeit.": "The right action at the right time.",
  "Mehr Conversion": "More conversion",
  "Bessere Erlebnisse, stärkere Bindung.": "Better experiences, stronger loyalty.",
  "Sandra fragt nach dem Sommer-Event": "Sandra asks about the summer event",
  "Hi liebes Team! Wann startet der Vorverkauf für das Sommer-Event?": "Hi team! When does presale start for the summer event?",
  "Hallo Sandra! Der Vorverkauf beginnt am 18. Mai um 10:00 Uhr. 🙂": "Hi Sandra! Presale starts on May 18 at 10:00. 🙂",
  "▱ Kanal: Chat": "▱ Channel: chat",
  "◷ Heute, 09:21": "◷ Today, 09:21",
  "Sandra zeigt Interesse am Sommer-Event. Die Nachricht landet im zentralen Posteingang.": "Sandra shows interest in the summer event. The message lands in the central inbox.",
  "FanMind erkennt den Kontext": "FanMind recognizes the context",
  "Status": "Status",
  "Interesse": "Interest",
  "Historie": "History",
  "48 Interaktionen": "48 interactions",
  "Letzter Kontakt": "Last contact",
  "Heute, 09:21": "Today, 09:21",
  "Positive Signale": "Positive signals",
  "hohes Interesse": "high interest",
  "FanMind vereint Profil, Historie und Verhalten zu einem klaren Bild – in Sekunden.": "FanMind combines profile, history and behavior into a clear picture – in seconds.",
  "KI schlägt die passende Antwort vor": "AI suggests the right response",
  "KI-Antwortvorschlag": "AI response suggestion",
  "Beta": "Beta",
  "Ja, als Mitglied bekommst du Early-Bird-Zugang und 10 % Rabatt. Wenn du möchtest, sende ich dir gleich alle Details zum Start.": "Yes, as a member you get early-bird access and a 10% discount. If you like, I can prepare all launch details for you.",
  "kurzer": "shorter",
  "freundlicher": "friendlier",
  "mit Memory": "with memory",
  "Gründe": "Reasons",
  "Early-Bird relevant": "early-bird relevant",
  "Mitglied & VIP-Potenzial": "member & VIP potential",
  "Unsere KI formuliert die beste Antwort – persönlich, relevant und auf Sandra abgestimmt.": "Our AI drafts the best response – personal, relevant and tailored to Sandra.",
  "Nächste beste Aktion vorgeschlagen": "Next best action suggested",
  "VIP-Infos + Friend-Ticket senden": "Send VIP info + friend ticket",
  "Empfohlen": "Recommended",
  "positiver Verlauf": "positive history",
  "hohe Conversion-Chance": "high conversion chance",
  "Follow-up planen": "Plan follow-up",
  "Erinnerung senden": "Send reminder",
  "Morgen, 09:00": "Tomorrow, 09:00",
  "Segmentzuweisung prüfen": "Review segment assignment",
  "Morgen, 12:00": "Tomorrow, 12:00",
  "FanMind empfiehlt die optimale Aktion und plant ein Follow-up – zur manuellen Freigabe.": "FanMind recommends the best action and plans a follow-up – for manual approval.",
  "Ergebnis: mehr Conversion, besseres Timing, mehr Impact": "Result: more conversion, better timing, more impact",
  "↑ +1,2 % vs. letzter Zeitraum": "↑ +1.2% vs. previous period",
  "Öffnungsrate": "Open rate",
  "Antwortquote": "Reply rate",
  "Sandra kauft ihr Ticket. Der richtige Zeitpunkt, die richtige Aktion – messbar mehr Erfolg.": "Sandra buys her ticket. The right timing and action create measurably better results.",
  "Mit Memory, KI und Follow-ups zum richtigen nächsten Schritt.": "Use memory, AI and follow-ups to reach the right next step.",
  "FanMind denkt mit. Für echte Verbindungen und messbare Ergebnisse.": "FanMind thinks with you. For real connections and measurable results.",
  "Mehr Relevanz": "More relevance",
  "Mehr Loyalität": "More loyalty",
  "Nächste Kontakte werden geplant, priorisiert und manuell freigegeben.": "Next contacts are planned, prioritized and manually approved.",
  "INTEGRATIONEN": "INTEGRATIONS",
  "Verbinde deine wichtigsten": "Connect your most important",
  "Kanäle.": "channels.",
  "FanMind bündelt E-Mail, Formulare und Roadmap-Kanäle in einem klaren Workflow. Kontext wird vorbereitet, geprüft und bleibt unter deiner Kontrolle.": "FanMind brings email, forms and roadmap channels into a clear workflow. Context is prepared, reviewed and stays under your control.",
  "E-Mail-Anfragen zentral bündeln und die Synchronisation transparent vorbereiten.": "Bundle email requests centrally and prepare synchronization transparently.",
  "Kontakte, Handles und Chat-Kontext für die spätere Synchronisation vorbereiten.": "Prepare contacts, handles and chat context for later synchronization.",
  "Server-, Profil- und Interaktionskontext für den späteren Abgleich vorbereiten.": "Prepare server, profile and interaction context for later matching.",
  "Profil- und Seitenkontakte für die spätere Synchronisation vorbereiten.": "Prepare profile and page contacts for later synchronization.",
  "Handles, Profile und Aktivität für den späteren Abgleich vorbereiten.": "Prepare handles, profiles and activity for later matching.",
  "Kommentare, Handles und Aktivitätsstände für die spätere Synchronisation vorbereiten.": "Prepare comments, handles and activity status for later synchronization.",
  "DM-Kontext, Profile und relevante Aktivität für die spätere Synchronisation vorbereiten.": "Prepare DM context, profiles and relevant activity for later synchronization.",
  "FanMind macht kontrollierte Multi-Channel-Arbeit transparent: angebundene Kanäle bleiben nutzbar, geplante Kanäle werden vorbereitet und erst nach technischer sowie rechtlicher Prüfung als aktiv gekennzeichnet. Unfertige Plattformen bleiben klar markiert.": "FanMind keeps controlled multi-channel work transparent: connected channels stay usable, planned channels are prepared and only marked active after technical and legal review. Unfinished platforms remain clearly labeled.",
  "DATENQUELLEN": "DATA SOURCES",
  "Bündelt • Ordnet • Bereitet vor": "Collects • Organizes • Prepares",
  "AKTIONEN & ERGEBNISSE": "ACTIONS & OUTCOMES",
  "✓ Keine Kreditkarte erforderlich": "✓ No credit card required",
  "✓ MVP klar gekennzeichnet": "✓ MVP clearly labeled",
  "✓ Kein automatischer Versand": "✓ No automatic sending",
  "ROADMAP & NÄCHSTE SCHRITTE": "ROADMAP & NEXT STEPS",
  "Was heute verfügbar ist – und was als Nächstes kommt.": "What is available today – and what comes next.",
  "RESPONSIVE EXPERIENCE": "RESPONSIVE EXPERIENCE",
  "Desktop, Tablet und Mobile –": "Desktop, tablet and mobile –",
  "überall klar.": "clear everywhere.",
  "FanMind ist für alle Bildschirmgrößen gestaltet: volle Übersicht am Desktop, schnelle Aktionen unterwegs und konsistente Fan-Daten für dein Team.": "FanMind is designed for every screen size: full overview on desktop, fast actions on the go and consistent fan data for your team.",
  "FanMind auf jedem Screen.": "FanMind on every screen.",
  "Volle Power, egal welches Gerät du nutzt.": "Full power, no matter what device you use.",
  "✓ Manuelle Freigabe": "✓ Manual approval",
  "Für Agenturen, Creator-Teams & Communities": "For agencies, creator teams & communities",
  "Wähle das passende": "Choose the right",
  "FanMind-Paket": "FanMind package",
  "für deinen Einstieg.": "for your start.",
  "FanMind ist ein KI-gestützter Antwort- und Memory-Assistent für Teams. Dieses MVP konzentriert sich auf Kontakte, KI-Antwortvorschläge, Memory, Follow-ups und CSV-Import.": "FanMind is an AI-assisted response and memory assistant for teams. This current-version focuses on contacts, AI response suggestions, memory, follow-ups and CSV import.",
  "Baue": "Build",
  "stärkere Fan-Beziehungen": "stronger fan relationships",
  "– mit weniger Chaos und besseren Antworten.": "– with less chaos and better replies.",
  "FanMind bündelt Kontakte, KI, Memory und Follow-ups an einem Ort.": "FanMind brings contacts, AI, memory and follow-ups together in one place.",
  "Pilot anfragen": "Request pilot",
  "✓ Schneller Einstieg": "✓ Fast start",
  "✓ Upgrade später möglich": "✓ Upgrade later",
  "DATENSCHUTZ & KONTROLLE": "PRIVACY & CONTROL",
  "KI-Unterstützung mit": "AI support with",
  "Kontrolle.": "control.",
  "FanMind unterstützt dein Team mit KI – während du die Kontrolle über Versand, Berechtigungen und Compliance jederzeit bewusst behältst.": "FanMind supports your team with AI while you stay in control of sending, permissions and compliance at all times.",
  "Sichere Daten": "Secure data",
  "Rollen & Rechte": "Roles & rights",
  "Regeln & Kontrollen": "Rules & controls",
  "EU-Fokus": "EU focus",
  "Freigabe & Zustimmung": "Approval & consent",
  "Smarte KI.": "Smart AI.",
  "Volle Kontrolle.": "Full control.",
  "Sichere Daten.": "Secure data.",
  "FanMind kombiniert KI-Unterstützung mit klaren Regeln, Transparenz und Datenschutz – für nachhaltiges Fan-Management.": "FanMind combines AI support with clear rules, transparency and privacy – for sustainable fan management.",
  "Datenschutz ansehen": "View privacy",
  "Demo buchen": "Book demo",
  "Vertrauen entsteht durch Sicherheit. FanMind liefert klare KI-Unterstützung mit bewusster Kontrolle.": "Trust starts with safety. FanMind provides clear AI support with deliberate control.",
  "FAQ": "FAQ",
  "Häufige Fragen zu": "Frequently asked questions about",
  "Antworten auf die häufigsten Fragen von Creator, Clubs, Agenturen und Brands – klar, ehrlich und auf den Punkt.": "Answers to the most common questions from creators, clubs, agencies and brands – clear, honest and to the point.",
  "Für Creator, Clubs, Agenturen und Brands.": "For creators, clubs, agencies and brands.",
  "Antworten für Teams mit wachsenden Communities.": "Answers for teams with growing communities.",
  "Noch Fragen?": "Questions?",
  "Unser Team ist für dich da – persönlich, schnell und zuverlässig.": "Our team is here for you – personal, fast and reliable.",
  "Das": "The",
  "KI-CRM für Creator, Clubs, Events und Fan-Communities.": "AI CRM for creators, clubs, events and fan communities.",
  "FanMind verbindet Kontakte, KI und Aktionen in einem System – für echte Fan-Beziehungen, mehr Conversion und nachhaltiges Wachstum.": "FanMind connects contacts, AI and actions in one system – for real fan relationships, more conversion and sustainable growth.",
  "Folge uns": "Follow us",
  "Bleib": "Stay",
  "einen Schritt voraus.": "one step ahead.",
  "Für Updates, Early-Access-Hinweise und Insights kannst du eine persönliche Anfrage an unser Team senden.": "For updates, access notes and insights, send a personal request to our team.",
  "E-Mail-Adresse eingeben": "Enter email address",
  "Early Access": "Request access",
  "🛡 Persönliche Anfrage statt automatischem Newsletter.": "🛡 Personal request instead of automated newsletter.",
  "© 2025 FanMind. Alle Rechte vorbehalten.": "© 2025 FanMind. All rights reserved.",
  "Datenschutz": "Privacy",
  "Zahlungsbedingungen": "Payment terms",
  "Impressum": "Legal notice",
  "AGB": "Terms",
  "Nach oben": "Back to top",

  "Alle Kanäle im Blick": "All channels in view",
  "Kontaktpunkte, Gesprächsnotizen und Kanal-Kontext werden zentral dokumentiert – dein Team behält alles nachvollziehbar im Blick.": "Contact points, conversation notes and channel context are documented centrally – your team keeps everything transparent.",
  "KI versteht deine Fans": "AI understands your fans",
  "Intelligente Vorschläge, geprüfte Antwortentwürfe und smarte Insights für bessere Beziehungen.": "Intelligent suggestions, reviewed response drafts and smart insights for better relationships.",
  "Segmentieren & personalisieren": "Segment & personalize",
  "Erstelle präzise Segmente und bereite die richtige Botschaft zur richtigen Zeit vor.": "Create precise segments and prepare the right message at the right time.",
  "Kampagnen vorbereiten": "Prepare campaigns",
  "Plane Kampagnenentwürfe als Vorschau – ohne automatischen Versand und ohne vollständige Versandfunktion.": "Plan campaign drafts as a preview – without automatic sending and without a full sending feature.",
  "Analytics auf der Roadmap": "Analytics on the roadmap",
  "Roadmap-Reports zeigen, welche Auswertungen später folgen; keine vollständige Analytics-Suite in der aktuellen Version.": "Roadmap reports show which analyses will follow later; no full analytics suite in the current version.",
  "Sicher & datenschutzorientiert": "Secure & privacy-oriented",
  "Deine Daten sind sicher, verschlüsselt und in europäischen Rechenzentren gehostet.": "Your data is secure, encrypted and hosted in European data centers.",
  "Zu viele Kanäle": "Too many channels",
  "E-Mails, Chats, Socials, WhatsApp und Formulare laufen parallel – aber nichts ist wirklich zentralisiert.": "Emails, chats, social channels, WhatsApp and forms run in parallel – but nothing is truly centralized.",
  "Informationen gehen verloren und Doppelarbeit entsteht.": "Information gets lost and duplicate work appears.",
  "Zu wenig Gedächtnis": "Too little memory",
  "Wichtige Details, Vorlieben und bisherige Interaktionen gehen unter. Jeder Kontakt fühlt sich wieder wie der erste an.": "Important details, preferences and previous interactions disappear. Every contact feels like the first one again.",
  "Keine persönliche Ansprache, weniger Bindung.": "Less personal communication, weaker loyalty.",
  "Zu wenig Timing": "Too little timing",
  "Kein Überblick über Follow-ups und Kampagnen. Chancen werden verpasst, Antworten kommen zu spät – oder gar nicht.": "No overview of follow-ups and campaigns. Opportunities are missed, replies arrive late – or not at all.",
  "Verpasste Gelegenheiten kosten Umsatz und Fans.": "Missed opportunities cost revenue and fans.",
  "Alle Kontakte": "All contacts",
  "an einem Ort.": "in one place.",
  "Kontext & Historie": "Context & history",
  "für jede Interaktion.": "for every interaction.",
  "KI-Vorschläge & Abläufe": "AI suggestions & workflows",
  "unterstützen dich.": "support you.",
  "Messbare Ergebnisse": "Measurable results",
  "und Wachstum.": "and growth.",
  "1. Kontakte": "1. Contacts",
  "Alle Fans und Interaktionen an einem Ort.": "All fans and interactions in one place.",
  "Alle Kontakte ansehen": "View all contacts",
  "2. Kontaktwissen": "2. Contact knowledge",
  "Wichtige Details, Interessen und Historie übersichtlich festhalten.": "Keep important details, interests and history clearly organized.",
  "Details ansehen": "View details",
  "3. KI-Antworten": "3. AI replies",
  "KI liefert passende Vorschläge. Du prüfst und gibst frei.": "AI provides relevant suggestions. You review and approve.",
  "KI entdecken": "Explore AI",
  "4. Follow-ups": "4. Follow-ups",
  "Nächste Aktionen, Erinnerungen und Aufgaben im Blick.": "Keep next actions, reminders and tasks in view.",
  "Alle Follow-ups": "All follow-ups",
  "5. Kampagnen": "5. Campaigns",
  "Kampagnen als geprüfte Entwürfe vorbereiten – Versand bleibt In Kürze.": "Prepare campaigns as reviewed drafts – sending remains planned.",
  "Roadmap ansehen": "View roadmap",
  "6. Analytics": "6. Analytics",
  "Roadmap-Ausblick für spätere Auswertungen und Wachstumssignale.": "Roadmap preview for future reporting and growth signals.",
  "Roadmap öffnen": "Open roadmap",
  "Kontakte": "Contacts",
  "Kanäle": "Channels",
  "Segmente": "Segments",
  "Kampagnen (Roadmap)": "Campaigns (roadmap)",
  "Analytics (Roadmap)": "Analytics (roadmap)",
  "KI Insights": "AI insights",
  "Einstellungen": "Settings",
  "Kontakt erfassen": "Capture contact",
  "Neue Kontakte aus Formularen, E-Mail, Chat oder Import sauber erfassen und zentral ablegen.": "Capture new contacts from forms, email, chat or import and store them centrally.",
  "Neuer Kontakt": "New contact",
  "Kontakt gespeichert": "Contact saved",
  "Kontaktwissen aufbauen": "Build contact knowledge",
  "Relevante Infos, Interessen und Interaktionen zentral speichern und sinnvoll verknüpfen.": "Store relevant information, interests and interactions centrally and connect them meaningfully.",
  "KI-Antwort erhalten": "Receive an AI reply",
  "Die KI liefert passende Antwortvorschläge zum Kontext – dein Team prüft und gibt frei.": "AI provides response suggestions based on context – your team reviews and approves.",
  "Freigabe durch Mensch erforderlich": "Human approval required",
  "Mehr Vorschläge anzeigen": "Show more suggestions",
  "Zur richtigen Zeit mit der passenden Botschaft – vorbereitet, priorisiert und manuell steuerbar.": "The right message at the right time – prepared, prioritized and manually controlled.",
  "Kanäle notieren: E-Mail-Kontext vorbereiten, weitere Kanäle Roadmap": "Note channels: prepare email context, additional channels on the roadmap",
  "Kanäle: E-Mail-Kontext vorbereitet, weitere Kanäle Roadmap": "Channels: email context prepared, additional channels on the roadmap",
  "Kampagne vorbereiten": "Prepare campaign",
  "Segmentierte Kampagnen als Roadmap-Vorschau vorbereiten, prüfen und ohne aktiven Versand einordnen.": "Prepare segmented campaigns as roadmap previews, review them and keep them without active sending.",
  "Geplant": "Planned",
  "Sommer-Event Early Bird": "Summer event early bird",
  "Versand: inaktiv / In Kürze": "Sending: inactive / planned",
  "Status: Vorschau geprüft": "Status: preview reviewed",
  "Analytics einordnen": "Frame analytics",
  "Roadmap-Auswertungen und Wachstumssignale transparent einordnen, ohne eine Vollsuite zu versprechen.": "Frame roadmap reporting and growth signals transparently without promising a full suite.",
  "Performance-Überblick": "Performance overview",
  "Roadmap-Auswertung: In Kürze": "Roadmap reporting: planned",
  "Wachstumssignale: Vorschau": "Growth signals: preview",
  "Antwortquote: Demo-Signal": "Reply rate: demo signal",
  "Insights für spätere Optimierung vorbereitet": "Insights prepared for later optimization",
  "Stärkere Beziehungen": "Stronger relationships",
  "Mehr Kontext. Mehr Relevanz. Mehr Vertrauen.": "More context. More relevance. More trust.",
  "Weniger Aufwand": "Less effort",
  "Bereite Routinen vor und fokussiere dich auf das Wesentliche.": "Prepare routines and focus on what matters.",
  "Höhere Conversion": "Higher conversion",
  "Die richtige Nachricht, zum richtigen Zeitpunkt.": "The right message at the right time.",
  "Volle Kontrolle": "Full control",
  "Transparente Daten, smarte Regeln und maximale Sicherheit.": "Transparent data, smart rules and maximum safety.",
  "Anfragen zentral bündeln.": "Bundle requests centrally.",
  "Im MVP": "In the MVP",
  "Chats als Roadmap-Kontext.": "Chats as roadmap context.",
  "Community-Signale strukturieren.": "Structure community signals.",
  "Nachrichten später einordnen.": "Classify messages later.",
  "DMs als Roadmap-Quelle.": "DMs as a roadmap source.",
  "Kommentare später abbilden.": "Map comments later.",
  "DMs und Storys bündeln.": "Bundle DMs and stories.",
  "Webformulare": "Web forms",
  "Formulare sauber erfassen.": "Capture forms cleanly.",
  "Bereit": "Ready",
  "Fans sinnvoll gruppieren.": "Group fans meaningfully.",
  "Nachfassaktionen vorbereiten.": "Prepare follow-up actions.",
  "Geprüfte Entwürfe planen.": "Plan reviewed drafts.",
  "Roadmap-Signale einordnen.": "Frame roadmap signals.",
  "Schneller verbunden": "Connected faster",
  "Kanäle zentral bündeln.": "Bundle channels centrally.",
  "Weniger manuelle Arbeit": "Less manual work",
  "Routinen schlank vorbereiten.": "Prepare routines efficiently.",
  "Zentrale Datenbasis": "Central data basis",
  "Kontext sauber zusammenführen.": "Bring context together cleanly.",
  "Sicher & zuverlässig": "Secure & reliable",
  "Nachvollziehbar für EU-Teams.": "Traceable for EU teams.",
  "Mobil arbeitsfähig": "Ready for mobile work",
  "Kontakte, Follow-ups und Insights bleiben auch unterwegs übersichtlich erreichbar.": "Contacts, follow-ups and insights remain easy to access on the go.",
  "Schnelle Reaktion unterwegs": "Fast response on the go",
  "Prioritäten, Erinnerungen und nächste Schritte helfen dir, keine Chance zu verpassen.": "Priorities, reminders and next steps help you avoid missing opportunities.",
  "Konsistente Fan-Daten auf jedem Gerät": "Consistent fan data on every device",
  "Ein gemeinsamer Kontext für dich und dein Team – vom großen Screen bis zum Smartphone.": "One shared context for you and your team – from big screens to smartphones.",
  "Zum Einstieg": "For starters",
  "Für Teams, die FanMind real testen möchten.": "For teams that want to test FanMind in practice.",
  "einmalig": "one-time",
  "Für Teams, die einen geführten Setup-/Pilotmonat als echten Testmonat möchten.": "For teams that want a guided setup/pilot month as a real test month.",
  "Geführter Setup-/Pilotmonat · kein Abo": "Guided setup/pilot month · no subscription",
  "Ziel: echter Testmonat mit begleitetem Setup": "Goal: real test month with guided setup",
  "Keine automatische Verlängerung, kein Abo, keine Bindung": "No automatic renewal, no subscription, no commitment",
  "Geführter Setup-/Pilotmonat": "Guided setup/pilot month",
  "1 Testmonat ohne automatische Verlängerung": "1 test month without automatic renewal",
  "Kostenlos testen · 1 Stunde Demo-Zugang": "Try for free · 1-hour demo access",
  "Keine Bindung": "No commitment",
  "Demo-Workspace, Kontakte/Fans und manuelle Kontakte testen": "Test demo workspace, contacts/fans and manual contacts",
  "CSV-Import minimal, Notizen und Kontaktwissen testen": "Test minimal CSV import, notes and contact knowledge",
  "Follow-ups, KI-Antwortvorschläge und Kommunikationsübersicht testen": "Test follow-ups, AI reply suggestions and communication overview",
  "Kanäle-Roadmap / Coming Soon sichtbar": "Channels roadmap / Coming Soon visible",
  "Ein Profil / ein produktiver Workspace": "One profile / one productive workspace",
  "Kontakte/Fans, manuelle Kontakte & CSV-Import minimal": "Contacts/fans, manual contacts & minimal CSV import",
  "Notizen und Kontaktwissen": "Notes and contact knowledge",
  "Follow-ups & Aufgaben inklusive /followups": "Follow-ups & tasks including /followups",
  "KI-Antwortvorschläge und Kommunikationsübersicht": "AI reply suggestions and communication overview",
  "Externe Social-Integrationen nur Roadmap/Preview": "External social integrations are roadmap/preview only",
  "Agency anfragen": "Request Agency",
  "Der Pilot ist vom kostenlosen 1-Stunden-Demo-Zugang getrennt: 990 € einmalig für 1 Testmonat, ohne Abo und ohne automatische Verlängerung.": "The pilot is separate from the free 1-hour demo access: €990 one-time for 1 test month, without subscription or automatic renewal.",

  "312 €/Monat": "€312/month",
  "Zwei Starter-Optionen im Paket": "Two Starter options in one package",
  "Starter Flex": "Starter Flex",
  "990 € Setup + 312 €/Monat": "€990 setup + €312/month",
  "jederzeit kündbar": "cancel anytime",
  "Für Teams, die ohne Laufzeitbindung starten möchten.": "For teams that want to start without a fixed term.",
  "Starter 12 Monate": "Starter 12 months",
  "0 € Setup + 312 €/Monat": "€0 setup + €312/month",
  "12 Monate Bindung": "12-month commitment",
  "Für Teams, die die Einrichtung ohne Setup-Gebühr starten und sich für 12 Monate binden.": "For teams that want to start setup without a setup fee and commit for 12 months.",
  "Starter Flex: 990 € Setup + 312 €/Monat · jederzeit kündbar": "Starter Flex: €990 setup + €312/month · cancel anytime",
  "Starter 12 Monate: 0 € Setup + 312 €/Monat · 12 Monate Bindung": "Starter 12 months: €0 setup + €312/month · 12-month commitment",
  "Beide Varianten gehören zum Starter-Paket": "Both options belong to the Starter package",
  "Starter wählen": "Choose Starter",
  "Growth wählen": "Choose Growth",
  "Beliebtester Plan": "Most popular plan",
  "Mensch prüft & sendet selbst": "Humans review & send themselves",
  "Du behältst die Kontrolle – FanMind unterstützt dich.": "You stay in control – FanMind supports you.",
  "Sicherheitsgrenze: kein automatisches Senden": "Safety boundary: no automatic sending",
  "FanMind sendet nicht automatisch. Du entscheidest, wann und wie.": "FanMind does not send automatically. You decide when and how.",
  "Datenschutzorientiert entwickelt": "Designed with privacy in mind",
  "Datenschutz steht im Fokus – Privacy by Design.": "Privacy is central – privacy by design.",
  "Roadmap klar gekennzeichnet": "Roadmap clearly labeled",
  "Geplante Funktionen sind transparent markiert.": "Planned features are labeled transparently.",
  "Sicherer KI-Einsatz": "Safe AI usage",
  "Prompts & Daten werden verantwortungsvoll verarbeitet.": "Prompts and data are processed responsibly.",
  "Produktkern": "product core",
  "Verfügbar": "Available",
  "Login & Registrierung": "Login & registration",
  "Dashboard & Kontakte": "Dashboard & contacts",
  "Manuelle Kontakte": "Manual contacts",
  "CSV-Import minimal": "Minimal CSV import",
  "Kontaktwissen": "Contact knowledge",
  "Kommunikationsübersicht": "Communication overview",
  "KI-Antwortvorschläge": "AI response suggestions",
  "Kontakt-Import": "Contact import",
  "Kontakt-Import & Datenqualität": "Contact import & data quality",
  "In Arbeit": "In progress",
  "Erweiterte CSV-Feldzuordnung": "Advanced CSV field mapping",
  "Kontakt-Mapping": "Contact mapping",
  "Import-Validierung": "Import validation",
  "Duplikaterkennung": "Duplicate detection",
  "Segment-Vorbereitung": "Segment preparation",
  "Segmente & Kampagnen": "Segments & campaigns",
  "Vorlagen": "Templates",
  "Team & Rollen": "Team & roles",
  "Performance-Übersicht": "Performance overview",
  "Workspaces / Multi-Workspace-Ausbau": "Workspaces / multi-workspace expansion",
  "Integrationen": "Integrations",
  "Mensch prüft vor Versand": "Humans review before sending",
  "Mensch prüft und sendet final selbst": "Humans review and send the final message themselves",
  "Qualität und Vertrauen stehen an erster Stelle.": "Quality and trust come first.",
  "FanMind bleibt ein manueller Copy-&-Open-Workflow: KI bereitet Antworten vor, der Mensch prüft und sendet final selbst.": "FanMind remains a manual copy-and-open workflow: AI prepares replies, humans review and send the final message themselves.",
  "Keine automatischen Nachrichten": "No automatic messages",
  "Keine Bots. Keine Massenmails. Kein Spam.": "No bots. No mass mails. No spam.",
  "Roadmap wird laufend erweitert": "Roadmap is continuously expanded",
  "Integrationen nach Prüfung": "Integrations after review",
  "Deine Wünsche und Feedback fließen ein.": "Your wishes and feedback flow in.",
  "Externe Kanalverbindungen sind geplant, in der Demo blockiert und werden erst nach technischer und rechtlicher Prüfung aktiviert.": "External channel connections are planned, blocked in the demo and will only be activated after technical and legal review.",

  "03 · Produkt-Showcase": "03 · Product showcase",
  "Ein Premium-Workspace für dein gesamtes": "A premium workspace for your entire",
  "Fan-Management.": "fan management.",
  "FanMind verbindet Kontakte, Kontaktwissen, KI-Vorschläge, Follow-ups und CSV-Import in einer kontrollierten Arbeitsfläche. Kampagnen und Analytics sind in der aktuellen Version als Vorschau markiert.": "FanMind connects contacts, contact knowledge, AI suggestions, follow-ups and CSV import in one controlled workspace. Campaigns and analytics are marked as previews in the current version.",
  "Kontakt seit 12.03.2025": "Contact since 03/12/2025",
  "Kontext": "Context",
  "Käufe": "Purchases",
  "Notizen": "Notes",
  "Entwurf": "Draft",
  "Sandra M.: „Gibt es noch Early-Bird Plätze für Member?“": "Sandra M.: “Are there still early-bird spots for members?”",
  "Ja! Als Mia Active Member erhältst du 10 % Rabatt in den ersten 48 Stunden. Bitte vor manueller Nutzung prüfen.": "Yes! As a Mia Active member, you receive a 10% discount in the first 48 hours. Please review before manual use.",
  "Freigabe nötig": "Approval needed",
  "Vorschlag prüfen": "Review suggestion",
  "Vorschau": "Preview",
  "Geplant: VIP + Buyer": "Planned: VIP + buyer",
  "Freigabe": "Approval",
  "Manuell": "Manual",
  "Versand": "Sending",
  "Inaktiv": "Inactive",
  "Gespeicherte Ansichten": "Saved views",
  "Reaktivierung": "Reactivation",
  "Premium-Käufer": "Premium buyers",
  "Verwalte alle Fan-Profile, Segmente und Interaktionen.": "Manage all fan profiles, segments and interactions.",
  "Aktive": "Active",
  "Follow-ups heute": "Follow-ups today",
  "24 hoch": "24 high",
  "⌕ Suche nach Name, Tag oder Profil …": "⌕ Search by name, tag or profile …",
  "Filter: Segment": "Filter: segment",
  "Sortierung: Fan Score": "Sort: fan score",
  "Alle": "All",
  "Heute fällig 128": "Due today 128",
  "Profil": "Profile",
  "Nächster Follow-up": "Next follow-up",
  "Gestern, 18:21": "Yesterday, 18:21",
  "Heute, 14:00": "Today, 14:00",
  "Überfällig": "Overdue",
  "Heute, 16:00": "Today, 16:00",
  "Gestern, 11:03": "Yesterday, 11:03",
  "Freitag, 12:00": "Friday, 12:00",
  "1–8 von 10.248 Kontakten": "1–8 of 10,248 contacts",
  "Heute": "Today",
  "Sandra M. · 10:00 · Hoch": "Sandra M. · 10:00 · High",
  "Lukas S. · 11:00 · Mittel": "Lukas S. · 11:00 · Medium",
  "Ella L. · überfällig": "Ella L. · overdue",
  "Tara J. · Freitag": "Tara J. · Friday",
  "Roadmap · keine Vollsuite in der aktuellen Version": "Roadmap · no full suite in the current version",
  "Roadmap anzeigen →": "View roadmap →",
  "Persönlicher Fan-Kontext": "Personal fan context",
  "Interaktionen, Tags und Notizen bleiben sichtbar, bevor dein Team antwortet.": "Interactions, tags and notes stay visible before your team replies.",
  "Nächste beste Aktion": "Next best action",
  "Priorisierte Aufgaben zeigen, welcher geprüfte Schritt jetzt Wirkung hat.": "Prioritized tasks show which reviewed step has impact now.",
  "KI-gestützte Segmentierung": "AI-assisted segmentation",
  "KI erkennt Muster und schlägt Segmente vor; dein Team prüft und nutzt sie gezielt.": "AI recognizes patterns and suggests segments; your team reviews and uses them intentionally.",
  "Geprüfte nächste Schritte": "Reviewed next steps",
  "Follow-ups und vorbereitete Entwürfe bleiben transparent nachvollziehbar.": "Follow-ups and prepared drafts remain transparent and traceable.",
  "Merkt sich Kaufhistorie, Interessen, Notizen und Kontaktverlauf pro Fan.": "Keeps purchase history, interests, notes and contact history per fan.",
  "Liefert passende Entwürfe – Mensch prüft, editiert und gibt frei.": "Delivers relevant drafts – a human reviews, edits and approves.",
  "Follow-up Queue": "Follow-up queue",
  "Bündelt fällige Aktionen nach Priorität, Owner und nächstem Schritt.": "Bundles due actions by priority, owner and next step.",
  "Kampagnen & Analytics": "Campaigns & analytics",
  "Als Vorschau sichtbar: Inhalte planen und Roadmap-Auswertungen prüfen.": "Visible as preview: plan content and review roadmap reporting.",
};

export function createFanMindTranslator(language: FanMindLanguage) {
  return (text: string) => (language === "en" ? englishCopy[text] ?? text : text);
}

export function localizeFanMindValue<T>(value: T, translate: (text: string) => string): T {
  if (typeof value === "string") {
    return translate(value) as T;
  }

  if (Array.isArray(value)) {
    return value.map((item) => localizeFanMindValue(item, translate)) as T;
  }

  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, nestedValue]) => [key, localizeFanMindValue(nestedValue, translate)]),
    ) as T;
  }

  return value;
}
