import type { FanMindLanguage } from "@/lib/fanmindCopy";

const workspaceTranslations: Record<string, string> = {
  "Willkommen zurück, Pilot Test 👋": "Welcome back, Pilot Test 👋",
  "Suche nach Name, Tag, Kanal, Sprache ...": "Search by name, tag, channel, language ...",
  "Suche": "Search",
  "Letzte 30 Tage · bald": "Last 30 days · soon",
  "Filter · bald": "Filter · soon",
  "+ Neuer Kontakt": "+ New contact",
  "+ Neuer Fan": "+ New fan",
  "Navigation": "Navigation",
  "Kanäle": "Channels",
  "Workspace": "Workspace",
  "Einstellungen": "Settings",
  "Vorschau": "Preview",
  "Suche nach Workspace, Profil, Paket ...": "Search workspace, profile, package ...",
  "Einstellungen speichern": "Save settings",
  "Nutzerpräferenzen": "User preferences",
  "Darstellung & Sprache": "Appearance & language",
  "Gespeichert pro Nutzer": "Saved per user",
  "Profil · Cookie · LocalStorage-Fallback": "Profile · cookie · localStorage fallback",
  "Wähle die Workspace-Sprache und eine dezente Helligkeit. Die Auswahl wird in deinem Nutzerprofil und als Cookie-Fallback gespeichert.": "Choose the workspace language and subtle brightness. Your selection is stored in your user profile and as a cookie fallback.",
  "Sprache": "Language",
  "Helligkeit": "Brightness",
  "Dark-Look": "Dark look",
  "Standard": "Default",
  "Heller": "Brighter",
  "Hell": "Light",
  "Gespeicherte Ansichten": "Saved views",
  "Top Fans": "Top fans",
  "Reaktivierung": "Reactivation",
  "Nutzerkarte": "User card",
  "Paket": "Package",
  "Abmelden": "Log out",
  "Demo Nutzer": "Demo User",
  "Aktiv": "Active",
  "Arbeits-Eingang": "Work inbox",
  "Neue Nachrichten": "New messages",
  "Alle Fans öffnen": "Open all fans",
  "Keine automatische Sendefunktion.": "No automatic sending.",
  "Gesamtfans": "Total fans",
  "Echte Kontakte im Workspace": "Real contacts in the workspace",
  "Aktive Fans": "Active fans",
  "Aktivitätslogik noch nicht aktiv": "Activity logic not active yet",
  "Offene Wiedervorlagen": "Open follow-ups",
  "Heute fällig": "Due today",
  "Rückmeldungen / Aufgaben": "Replies / tasks",
  "Laufende Kampagnen": "Running campaigns",
  "Kampagnen nicht aktiv": "Campaigns not active",
  "Reaktivierung noch nicht aktiv": "Reactivation not active yet",
  "Conversion Rate": "Conversion rate",
  "Conversion-Logik noch nicht aktiv": "Conversion logic not active yet",
  "CSV importieren": "Import CSV",
  "Name": "Name",
  "Status": "Status",
  "Tags": "Tags",
  "Angelegt": "Created",
  "Nächster Follow-up": "Next follow-up",
  "Antwortkanal": "Reply channel",
  "Neu": "New",
  "Käufer": "Buyer",
  "Inaktiv": "Inactive",
  "Nicht drängen": "Do not push",
  "Zur Fanliste": "Back to fan list",
  "← Zurück zur Fanliste": "← Back to fan list",
  "Kontaktdetail mit echten Workspace-Daten": "Contact detail with real workspace data",
  "Fans und Nachrichten suchen ...": "Search fans and messages ...",
  "Fan-Aktionen": "Fan actions",
  "Demo Modus": "Demo Mode",
  "Externe Verbindungen deaktiviert": "External connections disabled",
  "Owner": "Owner",
  "Letzter Kontakt": "Last contact",
  "Kontakt seit": "Contact since",
  "Primärkanal": "Primary channel",
  "Offene Follow-ups": "Open follow-ups",
  "Unified Inbox Timeline": "Unified Inbox Timeline",
  "Kanalübergreifender Verlauf": "Cross-channel history",
  "Demo-Modus: Externe Kanalzugriffe sind deaktiviert. KI-Vorschläge und interne Bearbeitung können getestet werden.": "Demo mode: External channel access is disabled. AI suggestions and internal editing can be tested.",
  "Notizen": "Notes",
  "Notizen speichern": "Save notes",
  "Zuletzt gespeichert": "Last saved",
  "Fan-Analyse-Report": "Fan analysis report",
  "Fan analysieren": "Analyze fan",
  "Noch kein Fan-Analyse-Report vorhanden.": "No fan analysis report yet.",
  "KI-Antwortvorschläge": "AI reply suggestions",
  "KI-Vorschläge erzeugen": "Generate AI suggestions",
  "Antwort kopieren": "Copy reply",
  "Kopiert": "Copied",
  "Der Mensch prüft und sendet final selbst. Keine automatische Sendefunktion.": "A human reviews and sends the final message. No automatic sending.",
};

export function wt(locale: FanMindLanguage, text: string): string {
  return locale === "en" ? workspaceTranslations[text] ?? text : text;
}
