version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:20"
      timezone: Europe/Zurich
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    commit-message:
      prefix: deps(web)
    groups:
      web-production-patches:
        dependency-type: production
        update-types:
          - patch
      web-development-patches:
        dependency-type: development
        update-types:
          - patch

  - package-ecosystem: npm
    directory: /apps/mobile
    schedule:
      interval: weekly
      day: monday
      time: "05:40"
      timezone: Europe/Zurich
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    commit-message:
      prefix: deps(mobile)
    groups:
      mobile-production-patches:
        dependency-type: production
        update-types:
          - patch
      mobile-development-patches:
        dependency-type: development
        update-types:
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Zurich
    open-pull-requests-limit: 3
    commit-message:
      prefix: deps(actions)
