import Link from "next/link";
import { notFound } from "next/navigation";
import { requirePlatformAdmin } from "@/lib/admin";
import { getAdminBillingWorkspace, listStripeInvoicesForWorkspace } from "@/lib/adminBilling";
import { getBillingStatusLabel } from "@/lib/billing";
import { getCommercialOptionLabel } from "@/lib/dashboardFeatures";
import { getStripeConfigStatus } from "@/lib/stripeBilling";
import { AdminBillingShell } from "../../AdminBillingShell";
import styles from "../../adminBilling.module.css";

function money(cents?: number | null) { return typeof cents === "number" ? (cents / 100).toLocaleString("de-DE", { style: "currency", currency: "EUR" }) : "—"; }
function date(value?: string | null) { return value ? new Date(value).toLocaleString("de-DE") : "—"; }
function Field({ label, value }: { label: string; value: React.ReactNode }) { return <div className={styles.field}><dt>{label}</dt><dd>{value || "—"}</dd></div>; }

export default async function AdminBillingWorkspaceDetailPage({ params }: { params: Promise<{ workspaceId: string }> }) {
  const user = await requirePlatformAdmin();
  const { workspaceId } = await params;
  const { workspace, error } = await getAdminBillingWorkspace(workspaceId);
  if (!workspace && !error) notFound();
  const stripe = getStripeConfigStatus();
  const invoices = workspace ? await listStripeInvoicesForWorkspace(workspace) : { invoices: [], error: null };

  return <AdminBillingShell user={user} title="Adminbereich" subtitle={`Workspace-Detail · Angemeldet als Admin: ${user.email ?? "Admin"}`}>
    <div className={styles.adminStack}>
      <section className={styles.hero}><div><span className={styles.eyebrow}>Workspace-Detail</span><h1>{workspace?.name ?? "Workspace"}</h1><p>{workspace?.owner_email ?? workspace?.owner_user_id ?? "Owner nicht hinterlegt"}</p></div><div className={styles.actions}><Link className={styles.buttonSecondary} href="/admin/billing">← Übersicht</Link>{workspace ? <span className={styles.badgeOk}>{getBillingStatusLabel(workspace.billing_status)}</span> : null}</div></section>
      {error ? <p className={styles.badgeWarn}>{error}</p> : null}
      {workspace ? <>
        <section className={styles.card}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>Paket & Abrechnung</span><h2>Plan, Option und Beträge</h2></div><span className={styles.chip}>{workspace.plan_id ?? "—"}</span></div><dl className={styles.detailGrid}><Field label="Workspace Name" value={workspace.name} /><Field label="Owner" value={workspace.owner_email ?? workspace.owner_user_id} /><Field label="Plan" value={workspace.plan_id} /><Field label="Option" value={getCommercialOptionLabel(workspace.commercial_option ?? "")} /><Field label="Setup-Kosten" value={money(workspace.setup_fee_cents)} /><Field label="Monatsbetrag" value={money(workspace.monthly_fee_cents)} /><Field label="Bindung" value={`${workspace.commitment_months ?? 0} Monate`} /><Field label="Workspace ID" value={workspace.id} /></dl></section>
        <section className={styles.card}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>Zahlungsstatus</span><h2>Status & Fristen</h2></div><span className={styles.badge}>{getBillingStatusLabel(workspace.billing_status)}</span></div><dl className={styles.detailGrid}><Field label="Billing Status" value={getBillingStatusLabel(workspace.billing_status)} /><Field label="Sperre / Grund" value={`${date(workspace.billing_suspended_at)} · ${workspace.billing_suspended_reason ?? "—"}`} /><Field label="Retry Count" value={workspace.billing_retry_count ?? 0} /><Field label="Next Retry" value={date(workspace.billing_next_retry_at)} /><Field label="Grace Until" value={date(workspace.billing_grace_until)} /><Field label="Last Payment" value={date(workspace.billing_last_payment_at)} /></dl></section>
        <section className={styles.card}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>Rechnungen</span><h2>Rechnungsinformationen</h2></div>{!stripe.hasSecretKey ? <span className={styles.badgeWarn}>Stripe fehlt</span> : <span className={styles.badgeOk}>Stripe aktiv</span>}</div><dl className={styles.detailGrid}><Field label="Letzte Rechnung" value={`${workspace.last_invoice_status ?? "—"} · ${money(workspace.last_invoice_amount_due_cents)}`} /><Field label="Bezahlt" value={money(workspace.last_invoice_amount_paid_cents)} /><Field label="Invoice ID" value={workspace.last_invoice_id} /><Field label="Invoice Links" value={<>{workspace.last_invoice_hosted_url ? <a href={workspace.last_invoice_hosted_url}>Hosted Invoice</a> : "—"} {workspace.last_invoice_pdf_url ? <a href={workspace.last_invoice_pdf_url}>PDF</a> : null}</>} /></dl>{invoices.error ? <p className={styles.badgeWarn}>{invoices.error}</p> : null}<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Datum</th><th>Status</th><th>Betrag</th><th>Links</th></tr></thead><tbody>{invoices.invoices.map((i) => <tr key={i.id}><td>{date(i.created)}</td><td>{i.status ?? "—"}</td><td>{money(i.amount_due)}</td><td>{i.hosted_invoice_url ? <a href={i.hosted_invoice_url}>Hosted</a> : null} {i.invoice_pdf ? <a href={i.invoice_pdf}>PDF</a> : null}</td></tr>)}</tbody></table></div></section>
        <section className={styles.card}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>Systemdaten</span><h2>Stripe-Daten</h2></div></div><dl className={styles.detailGrid}><Field label="Stripe Customer ID" value={workspace.stripe_customer_id} /><Field label="Stripe Subscription ID" value={workspace.stripe_subscription_id} /><Field label="Stripe Checkout Session ID" value={workspace.stripe_checkout_session_id} /><Field label="Aktualisiert" value={date(workspace.billing_updated_at)} /></dl></section>
        <section className={styles.card}><div className={styles.cardHeader}><div><span className={styles.eyebrow}>Admin-Aktionen</span><h2>Aktionen & Notizen</h2></div></div><div className={styles.actions}><form action={`/api/admin/billing/workspaces/${workspace.id}/suspend`} method="post"><button className={styles.buttonDanger}>Sperren</button></form><form action={`/api/admin/billing/workspaces/${workspace.id}/unsuspend`} method="post"><button className={styles.buttonSecondary}>Entsperren</button></form></div><form action={`/api/admin/billing/workspaces/${workspace.id}/mark-paid`} method="post" className={styles.formGrid}><h3>Zahlung als eingegangen markieren</h3><label>Zahlungsquelle<select className={styles.select} name="payment_source" defaultValue="bank_transfer"><option value="bank_transfer">Banküberweisung</option><option value="stripe_confirmed">Stripe bestätigt</option><option value="cash_or_other">Bar/anderer Weg</option><option value="credit_note">Gutschrift/Kulanz</option><option value="correction">Korrektur</option></select></label><label>Betrag optional<input className={styles.input} name="amount" inputMode="decimal" /></label><label>Referenz/Notiz optional<input className={styles.input} name="reference" /></label><label>Datum optional<input className={styles.input} name="paid_at" type="date" /></label><label><input type="checkbox" name="lift_payment_suspension" value="true" defaultChecked={workspace.billing_status !== "manual_suspended"} disabled={workspace.billing_status === "manual_suspended"} /> Zahlungsbedingte Sperre aufheben</label><button className={styles.buttonPrimary}>Zahlung verbuchen</button></form><form action={`/api/admin/billing/workspaces/${workspace.id}/note`} method="post" className={styles.formGrid}><h3>Admin-Notiz</h3><textarea className={styles.textarea} name="note" defaultValue={workspace.billing_admin_note ?? ""} rows={5} /><button className={styles.buttonPrimary}>Admin-Notiz speichern</button></form></section>
      </> : null}
    </div>
  </AdminBillingShell>;
}
