#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { createReadStream, createWriteStream } from 'node:fs';
import { mkdir, mkdtemp, rm, stat, writeFile } from 'node:fs/promises';
import { hostname, tmpdir } from 'node:os';
import { join, basename, dirname } from 'node:path';
import { spawn } from 'node:child_process';

const VERSION = 'phase5-backup-worker-1';
const JOBS = new Set(['backup_server_config','backup_database','backup_storage','backup_full','verify_backup']);
const BACKUP_ROOT = process.env.FANMIND_BACKUP_ROOT || '/var/backups/fanmind';
const WORKER_ID = process.env.FANMIND_BACKUP_WORKER_ID || `fanmind-backup-${hostname() || 'worker'}-${process.pid}`;
const SUPABASE_URL = required('NEXT_PUBLIC_SUPABASE_URL');
const SERVICE_KEY = required('SUPABASE_SERVICE_ROLE_KEY');
let stopping = false;
process.on('SIGTERM', () => { stopping = true; log('info', 'sigterm_received'); });
process.on('SIGINT', () => { stopping = true; log('info', 'sigint_received'); });

function required(name) { const value = process.env[name]; if (!value) throw new Error(`${name}_missing`); return value; }
function log(level, event, meta = {}) { console.log(JSON.stringify({ ts:new Date().toISOString(), level, event, worker_id:WORKER_ID, ...redact(meta) })); }
function redact(value) { return JSON.parse(JSON.stringify(value, (k, v) => /key|secret|password|token|pgpass|authorization/i.test(k) ? '[redacted]' : v)); }
function restUrl(table, query='') { return `${SUPABASE_URL.replace(/\/$/,'')}/rest/v1/${table}${query}`; }
function headers(extra={}) { return { apikey:SERVICE_KEY, Authorization:`Bearer ${SERVICE_KEY}`, 'Content-Type':'application/json', Prefer:'return=representation', ...extra }; }
async function api(path, init={}) { const r = await fetch(path, { ...init, headers: headers(init.headers || {}) }); if (!r.ok) throw new Error(`supabase_${r.status}`); return r.status === 204 ? null : r.json(); }
async function rpc(name, body) { return api(`${SUPABASE_URL.replace(/\/$/,'')}/rest/v1/rpc/${name}`, { method:'POST', body:JSON.stringify(body) }); }
function run(bin, args, opts={}) { return new Promise((resolve, reject) => { const p = spawn(bin, args, { shell:false, stdio:['ignore','pipe','pipe'], env:{...process.env, ...(opts.env || {})}, cwd:opts.cwd }); p.stderr.on('data', () => {}); p.on('close', code => code === 0 ? resolve() : reject(new Error(`${basename(bin)}_exit_${code}`))); }); }
async function sha256(file) { const h = createHash('sha256'); await new Promise((res, rej) => createReadStream(file).on('data', d=>h.update(d)).on('error', rej).on('end', res)); return h.digest('hex'); }
async function size(file) { return (await stat(file)).size; }
async function insert(table, row) { return (await api(restUrl(table), { method:'POST', body:JSON.stringify(row) }))[0]; }
async function patch(table, id, row) { return api(restUrl(table, `?id=eq.${encodeURIComponent(id)}`), { method:'PATCH', body:JSON.stringify(row) }); }
async function notify(severity, title, message, source, technical_reference) { await insert('admin_notifications', { category:severity, severity, title, message, source, technical_reference, metadata:{ worker_id:WORKER_ID } }).catch(e => log('warn','notification_failed',{error:e.message})); }
async function audit(action, outcome, metadata={}) { await insert('operations_audit_log', { action, outcome, target_table:'admin_operation_jobs', severity: outcome === 'success' ? 'info' : 'warning', metadata }).catch(()=>{}); }
async function heartbeat(status='healthy') { await insert('system_health_events', { component:'backup_worker', status, severity:status==='healthy'?'info':'warning', summary:`Backup worker heartbeat: ${status}`, technical_reference:WORKER_ID, metadata:{ version:VERSION } }).catch(()=>{}); }
async function encryptedFinalize(clearFile, type, manifest) { const recipientFile = process.env.FANMIND_BACKUP_PUBLIC_KEY_FILE; if (!recipientFile) throw new Error('backup_public_key_missing'); const encrypted = `${clearFile}.age`; await run(process.env.FANMIND_AGE_BIN || 'age', ['-R', recipientFile, '-o', encrypted, clearFile]); await rm(clearFile, { force:true }); const checksum = await sha256(encrypted); await writeFile(`${encrypted}.sha256`, `${checksum}  ${basename(encrypted)}\n`, { mode:0o600 }); const s = await size(encrypted); return { path:encrypted, sha256:checksum, size_bytes:s, manifest:{...manifest, encrypted:true, format_version:1, worker_version:VERSION, backup_type:type} }; }
async function tarValidate(file) { await run('tar', ['-tzf', file]); }
async function createServerConfig(tmp) { const out = join(tmp, `fanmind-server-config-${Date.now()}.tar.gz`); const paths = ['/var/www/fanmind/.env.production','/root/.pm2/dump.pm2','/etc/nginx','/etc/systemd/system','/etc/fanmind-backup']; await run('tar', ['--ignore-failed-read','--warning=no-file-changed','-czf', out, ...paths]); await tarValidate(out); return encryptedFinalize(out, 'server_config', { included:['env_production','pm2_dump','nginx','systemd_units','backup_config_public'] }); }
async function createDatabase(tmp) { const out = join(tmp, `fanmind-database-${Date.now()}.dump`); const pgDump = process.env.FANMIND_PG_DUMP_BIN || '/usr/lib/postgresql/17/bin/pg_dump'; const pgRestore = process.env.FANMIND_PG_RESTORE_BIN || '/usr/lib/postgresql/17/bin/pg_restore'; const env = { PGPASSFILE: required('FANMIND_BACKUP_PGPASSFILE') }; const args = ['--format=custom','--no-owner','--no-privileges','--file',out,'--host',required('FANMIND_BACKUP_DB_HOST'),'--port',process.env.FANMIND_BACKUP_DB_PORT || '5432','--username',required('FANMIND_BACKUP_DB_USER'),required('FANMIND_BACKUP_DB_NAME')]; await run(pgDump, args, { env }); await run(pgRestore, ['--list', out], { env }); return encryptedFinalize(out, 'database', { pg_format:'custom', validated_with:'pg_restore --list' }); }
async function listStorage(prefix='') { const body = { prefix, limit:1000, offset:0, sortBy:{ column:'name', order:'asc' } }; const rows = await api(`${SUPABASE_URL.replace(/\/$/,'')}/storage/v1/object/list/fanmind-assets`, { method:'POST', body:JSON.stringify(body), headers:{ Authorization:`Bearer ${SERVICE_KEY}`, apikey:SERVICE_KEY } }); return rows || []; }
async function walkStorage(prefix='', acc=[]) { for (const item of await listStorage(prefix)) { const path = prefix ? `${prefix}/${item.name}` : item.name; if (!item.id && !item.metadata?.size) await walkStorage(path, acc); else acc.push({ path, ...item }); } return acc; }
async function createStorage(tmp) { const root = join(tmp, 'storage'); await mkdir(root, { recursive:true, mode:0o700 }); const objects = await walkStorage(); const files=[]; for (const obj of objects) { const r = await fetch(`${SUPABASE_URL.replace(/\/$/,'')}/storage/v1/object/fanmind-assets/${encodeURI(obj.path)}`, { headers:{ Authorization:`Bearer ${SERVICE_KEY}`, apikey:SERVICE_KEY } }); if (!r.ok) throw new Error('storage_download_failed'); const target = join(root, obj.path); await mkdir(dirname(target), { recursive:true, mode:0o700 }); await new Promise((res, rej) => { const w = createWriteStream(target, { mode:0o600 }); if (!r.body?.pipeTo) { rej(new Error('stream_unavailable')); return; } r.body.pipeTo(new WritableStream({ write(c){ w.write(Buffer.from(c)); }, close(){ w.end(); res(); }, abort:rej })).catch(rej); }); files.push({ path:obj.path, size:await size(target), content_type:obj.metadata?.mimetype || null, created_at:obj.created_at, updated_at:obj.updated_at, sha256:await sha256(target) }); }
 const manifest = { bucket:'fanmind-assets', object_count:files.length, total_size_bytes:files.reduce((a,f)=>a+f.size,0), files }; await writeFile(join(root,'manifest.json'), JSON.stringify(manifest,null,2), { mode:0o600 }); const out = join(tmp, `fanmind-storage-${Date.now()}.tar.gz`); await run('tar', ['-czf', out, '-C', root, '.']); await tarValidate(out); return encryptedFinalize(out, 'storage', manifest); }
async function createFull(tmp) { const parts=[]; parts.push(await createServerConfig(tmp)); parts.push(await createDatabase(tmp)); parts.push(await createStorage(tmp)); const manifest = { created_at:new Date().toISOString(), production_commit:process.env.FANMIND_RELEASE_COMMIT || process.env.GITHUB_SHA || 'unknown', worker_version:VERSION, parts:parts.map(p=>({ path:basename(p.path), sha256:p.sha256, size_bytes:p.size_bytes, manifest:p.manifest })) }; const clear = join(tmp, `fanmind-full-${Date.now()}.manifest.json`); await writeFile(clear, JSON.stringify(manifest,null,2), { mode:0o600 }); return encryptedFinalize(clear, 'full', manifest); }
async function offsite(file) { if (process.env.FANMIND_BACKUP_OFFSITE_ENABLED !== 'true') return { status:'not_configured' }; const remote = required('FANMIND_BACKUP_RCLONE_REMOTE'); const remotePath = process.env.FANMIND_BACKUP_REMOTE_PATH || 'fanmind'; const config = process.env.FANMIND_BACKUP_RCLONE_CONFIG; const args = [...(config ? ['--config', config] : []), 'copyto', file, `${remote}:${remotePath}/${basename(file)}`]; await run(process.env.FANMIND_RCLONE_BIN || 'rclone', args); return { status:'uploaded', reference:`${remote}:${remotePath}/${basename(file)}` }; }
async function handle(job) { if (!JOBS.has(job.job_type)) throw new Error('job_type_not_allowed'); await patch('admin_operation_jobs', job.id, { status:'running', started_at:new Date().toISOString(), lease_until:new Date(Date.now()+900000).toISOString() }); const tmp = await mkdtemp(join(tmpdir(), 'fanmind-backup-')); try { await mkdir(BACKUP_ROOT, { recursive:true, mode:0o700 }); const start = Date.now(); let result; if (job.job_type === 'backup_server_config') result = await createServerConfig(tmp); else if (job.job_type === 'backup_database') result = await createDatabase(tmp); else if (job.job_type === 'backup_storage') result = await createStorage(tmp); else if (job.job_type === 'backup_full') result = await createFull(tmp); else result = { path:String(job.result_reference || ''), sha256:'', size_bytes:0, manifest:{ verification:'queued_only' } }; const final = join(BACKUP_ROOT, basename(result.path)); await run('mv', [result.path, final]); const off = await offsite(final).catch(e => ({ status:'failed', error:e.message })); const status = off.status === 'not_configured' ? 'offsite_pending' : off.status === 'failed' ? 'degraded' : 'succeeded'; const run = await insert('backup_runs', { backup_type: result.manifest.backup_type === 'server_config' ? 'server_config' : result.manifest.backup_type, status, severity: status === 'succeeded' ? 'info':'warning', finished_at:new Date().toISOString(), storage_reference:final, checksum_reference:`${final}.sha256`, sha256:result.sha256, size_bytes:result.size_bytes, validation_status:'passed', offsite_status:off.status, offsite_reference:off.reference || null, job_id:job.id, worker_id:WORKER_ID, duration_ms:Date.now()-start, manifest:result.manifest }); await patch('admin_operation_jobs', job.id, { status:'succeeded', finished_at:new Date().toISOString(), result_reference:run.id, lease_until:null }); await notify(status === 'succeeded' ? 'info':'warning', status === 'succeeded' ? 'Backup erfolgreich' : 'Backup lokal erfolgreich, Offsite ausstehend', `${job.job_type} wurde verarbeitet.`, 'backup_worker', run.id); await audit(job.job_type, 'success', { backup_run_id:run.id, offsite_status:off.status }); } finally { await rm(tmp, { recursive:true, force:true }); } }
async function loop() { log('info','worker_start',{version:VERSION}); while (!stopping) { await heartbeat(); const job = await rpc('claim_admin_backup_job', { p_worker_id:WORKER_ID, p_lease_seconds:900 }).catch(e => { log('warn','claim_failed',{error:e.message}); return null; }); if (!job) { await new Promise(r=>setTimeout(r, Number(process.env.FANMIND_BACKUP_POLL_MS || 30000))); continue; } log('info','job_claimed',{job_id:job.id, job_type:job.job_type}); try { await handle(job); } catch(e) { const msg = e instanceof Error ? e.message.replace(/[^a-zA-Z0-9_.:-]/g,'_').slice(0,160) : 'unknown_error'; await patch('admin_operation_jobs', job.id, { status:'failed', finished_at:new Date().toISOString(), error_code:msg.split('_')[0] || 'backup_failed', error_message:msg, lease_until:null }).catch(()=>{}); await notify('critical','Backup fehlgeschlagen', `${job.job_type} ist fehlgeschlagen.`, 'backup_worker', job.id); await audit(job.job_type, 'failure', { error_code:msg }); log('error','job_failed',{job_id:job.id,error:msg}); } } log('info','worker_stop'); }
loop().catch(e => { log('error','fatal',{error:e.message}); process.exit(2); });
